apiVersion: v1
kind: Namespace
metadata:
  name: ee
  labels:
    environmentId: env_295214e3-bf69-4188-8e13-0eb1daa3ed08
    projectId: project_14b5198c-251f-44c3-8685-04e102854002
    projectName: pawara
    environmentName: f
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
