apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-app-2-v1-0-0
  labels:
    app: test-app-2-v1-0-0
    applicationId: app_0baaca20-6eff-436f-893e-1bb2f0fd91f6
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_defdd726-16b5-42b9-afaf-d1096744e902
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-app-2-v1-0-0
