apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: bb-app-1-main
      imagePullPolicy: Always
      imageRegistry: aaaa/bb-app-1
      imagePullSecretName: imagepull-docker
      credentialId: credential_20cfdd35-316e-4c08-8844-65c97e054859
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: bb-app-1
    version: v1.0.0
    applicationId: app_164ae7b6-b0c2-4871-a9d8-a5d033e28453
    projectId: project_d6eb94b5-d39d-4dc5-8c15-602de5677592
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_af0778dd-0e4a-44ba-899e-d62b175e6d52
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: bb-app-1
  serviceType: ClusterIP
  version: v1.0.0
  namespace: pawara-4-dev
