openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
        '404':
          description: Users not found
        '500':
          description: Internal server error
    post:
      summary: Create a new user
      responses:
        '200':
          description: User created successfully
        '404':
          description: User creation failed
        '500':
          description: Internal server error
components: {}
servers:
  - url: https://api.example.com/v1