apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-app-1-v1-0-0
  labels:
    app: test-app-1-v1-0-0
    applicationId: app_4503e955-e50a-4a1f-a582-7d13f390d0a7
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_defdd726-16b5-42b9-afaf-d1096744e902
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-app-1-v1-0-0
