openapi: 3.0.0
info:
  title: Merged API Specification
  version: 1.0.0
paths:
  /add/{user_id}/{coffee_id}:
    delete:
      parameters:
        - description: ID of the user
          in: path
          name: user_id
          required: true
          schema:
            type: string
        - description: ID of the coffee
          in: path
          name: coffee_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    properties:
                      __v:
                        type: integer
                      _id:
                        type: string
                      coffeeId:
                        type: string
                      createdAt:
                        type: string
                      quantity:
                        type: integer
                      userId:
                        type: string
                    type: object
                  message:
                    type: string
                type: object
          description: OK
      summary: Remove From Cart
    post:
      parameters:
        - description: ID of the user
          in: path
          name: user_id
          required: true
          schema:
            type: string
        - description: ID of the coffee
          in: path
          name: coffee_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    properties:
                      __v:
                        type: integer
                      _id:
                        type: string
                      coffeeId:
                        type: string
                      createdAt:
                        type: string
                      quantity:
                        type: integer
                      userId:
                        type: string
                    type: object
                  message:
                    type: string
                type: object
          description: OK
      summary: Add to Cart
  /health:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                type: object
          description: OK
      summary: Get Health
  /{user_id}:
    delete:
      parameters:
        - description: ID of the user
          in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    properties:
                      acknowledged:
                        type: boolean
                      deletedCount:
                        type: integer
                    type: object
                  message:
                    type: string
                type: object
          description: OK
      summary: Delete Cart
    get:
      parameters:
        - description: ID of the user
          in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    items:
                      properties:
                        __v:
                          type: integer
                        _id:
                          type: string
                        coffeeId:
                          type: string
                        createdAt:
                          type: string
                        quantity:
                          type: integer
                        userId:
                          type: string
                      type: object
                    type: array
                  message:
                    type: string
                type: object
          description: OK
      summary: Get Cart
  /user:
    get:
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      summary: Get User
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      summary: Create User
    put:
      parameters:
        - description: ID of the user
          in: path
          name: user_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      summary: Update User
components:
  schemas: {}