openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found
        '500':
          description: Internal server error
components: {}