apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: hhh-main
      imagePullPolicy: Always
      imageRegistry: test/hhh
      imagePullSecretName: imagepull-docker
      credentialId: credential_153916e4-2463-4c33-a422-b4fff74f499c
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: hhh
    version: v1.0.0
    applicationId: app_258f852b-79bb-4cb4-95ca-f058236b0045
    projectId: project_14b5198c-251f-44c3-8685-04e102854002
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    environmentId: env_ad578c91-042f-4148-946b-d68a3efe3bdd
    environmentName: c
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: hhh
  serviceType: ClusterIP
  version: v1.0.0
  namespace: c
