apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: hhh-v1-0-0
    applicationId: app_258f852b-79bb-4cb4-95ca-f058236b0045
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_14b5198c-251f-44c3-8685-04e102854002
  name: hhh-v1-0-0
spec:
  selector:
    app: hhh-v1-0-0
