apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: test-app-3-v1-0-0
    applicationId: app_57003dbd-04da-44c4-98f0-8fcd12ba64ac
    version: v1.0.0
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_defdd726-16b5-42b9-afaf-d1096744e902
  name: test-app-3-v1-0-0
spec:
  selector:
    app: test-app-3-v1-0-0
