apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: asds-main
      imagePullPolicy: Always
      imageRegistry: 1/1
      imagePullSecretName: imagepull-docker
      credentialId: credential_b3c8aa81-405f-4a45-95a8-de0ed27318b1
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: asds
    version: v1.0.0
    applicationId: app_68b0c052-44cb-4b7b-be90-4a34050f7a77
    projectId: project_ffe2681e-3418-401a-9222-e7da84cb8ed6
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    environmentId: env_7cf32ffc-1841-4b3e-a964-3621660fcfa4
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: asds
  serviceType: ClusterIP
  version: v1.0.0
  namespace: sda-prod
