apiVersion: v1
kind: Namespace
metadata:
  name: a
  labels:
    environmentId: env_a8b126bb-b9ee-4e70-a59e-523e4117d1d2
    projectId: project_14b5198c-251f-44c3-8685-04e102854002
    projectName: pawara
    environmentName: a
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
