apiVersion: v1
kind: Namespace
metadata:
  name: e
  labels:
    environmentId: env_1c489efd-b2be-4702-b839-30d8c2d6ceb5
    projectId: project_14b5198c-251f-44c3-8685-04e102854002
    projectName: pawara
    environmentName: e
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
