apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_14b5198c-251f-44c3-8685-04e102854002
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_14b5198c-251f-44c3-8685-04e102854002
spec:
  skyuControlPlaneAPI:
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_14b5198c-251f-44c3-8685-04e102854002
  provider: docker
  secretRef: secret_761d4cbf-c9e8-41f4-9077-30e9795deaa5
