apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_ffe2681e-3418-401a-9222-e7da84cb8ed6
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_ffe2681e-3418-401a-9222-e7da84cb8ed6
spec:
  skyuControlPlaneAPI:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_ffe2681e-3418-401a-9222-e7da84cb8ed6
  provider: docker
  secretRef: 9f398f31-d21a-4445-ad42-aaccf28a674d
