apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_f9d4e765-bbc7-41bf-bec2-e805d8d48285
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_f9d4e765-bbc7-41bf-bec2-e805d8d48285
spec:
  skyuControlPlaneAPI:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_f9d4e765-bbc7-41bf-bec2-e805d8d48285
  provider: docker
  secretRef: 0a0fd266-4f19-450e-a914-277607f5b5e3
