apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_081baac5-2450-46ed-bff0-466149d38abd
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_081baac5-2450-46ed-bff0-466149d38abd
spec:
  skyuControlPlaneAPI:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_081baac5-2450-46ed-bff0-466149d38abd
  provider: docker
  secretRef: d948a0ca-1fcf-4875-9139-c0fdb3e723b1
