apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_52a258ba-ed31-4cf7-9362-70a309b342aa
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_52a258ba-ed31-4cf7-9362-70a309b342aa
spec:
  skyuControlPlaneAPI:
    organizationId: org_83167af8-ae98-451b-972e-dca861896824
    projectId: project_52a258ba-ed31-4cf7-9362-70a309b342aa
  provider: docker
  secretRef: secret_feca4cf8-ee9f-480f-949b-e92011ffaef2
