apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_d6eb94b5-d39d-4dc5-8c15-602de5677592
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_d6eb94b5-d39d-4dc5-8c15-602de5677592
spec:
  skyuControlPlaneAPI:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_d6eb94b5-d39d-4dc5-8c15-602de5677592
  provider: docker
  secretRef: secret_e63b750f-8b4a-433d-8b41-763ebbfd5d46
