apiVersion: configs.skyu.io/v1
kind: SkyUImagePullSecret
metadata:
  name: imagepull-docker
  labels:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_3be0574b-7ed8-43cf-83e5-4278379af929
  namespace: skyu-system
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: project-id=project_3be0574b-7ed8-43cf-83e5-4278379af929
spec:
  skyuControlPlaneAPI:
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_3be0574b-7ed8-43cf-83e5-4278379af929
  provider: docker
  secretRef: 59086fbb-e387-4f8a-b2d6-06e03af06c1f
